### ISSUE TITLE
Please fix it for future Composer v2.0

### ISSUE THREAD

**Issue by oriceon** [Eugene-Melbourne/laravel-csv-generator#4]
Deprecation Notice: Class LaravelCsvGenerator\LaravelCsvGenerator located in /vendor/eugene-melbourne/laravel-csv-generator/src\LaravelCsvGenerator.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar://composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:185

**Comment by Eugene-Melbourne** [comment]
It is done.
